### ISSUE TITLE
Switch from FMOD Ex to OpenAL-Soft

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#10]
I found that Debian and Ubuntu don't include FMOD as it is actually a closed-source library, so I will be moving in the direction of OpenAL-Soft soon instead. 

For MIDI support, I'll use either WildMIDI or FluidSynth. I don't know if there will be any significant changes to the project's Ogg support when using OpenAL-Soft. In the worst case, all of the .ogg sound files would be converted to another (hopefully lossless) format.

**Comment by psi29a** [comment]
You can use libogg (or another library) to stream it to openal-soft. Here is an article about setting it up (ogg/openal):
http://benbritten.com/2010/05/04/streaming-in-openal/

If you need help... stop by OpenMW's forum or IRC channel and talk with Chris/Kcat who is our resident OpenAL expert (and lead developer of OpenAL-Soft itself). 

We use FFmpeg to support _every_ fileformat under the sun and stream it to OpenAL to do the rest.

I don't think you need FFmpeg if you only support OGG, that is why I recommended libogg.

**Comment by psi29a** [comment]
BTW... OpenMW wishes you success on the project! :D

https://forum.openmw.org/viewtopic.php?f=4&t=3606

**Comment by afritz1** [comment]
Thanks! Yes, this is my first real project, and as such I expect to make a lot of naive mistakes along the way. It's great having such open access to experts on subjects like audio and cross-platform issues. I'm more oriented towards graphics programming; hence the plan to make my own ray tracer. It just seemed like a good idea since Arena has so little geometry to render and I know more about OpenCL than OpenGL.

I am glad I decided to go with C++ instead of C#, since I have a feeling it would've been harder to keep things compatible between Visual Studio and Mono than between Visual Studio and GCC.

**Comment by psi29a** [comment]
Once you feel you are ready... I can help get opentesarea into Debian/Ubuntu and help with porting to other platforms as well. :)

Congratulations and good luck on the project by the way!

**Comment by Ragora** [comment]
Mono implements the standard .NET libraries and for game specific routines, MonoGame runs on Windows as well and is at least partially API compatible with XNA. The latter I know is true from first hand experience of experimentally porting [a project of mine](https://github.com/Ragora/YoshisIsland) from .NET to Linux via Mono.

**Comment by afritz1** [comment]
I used [OpenCL.Net](https://www.nuget.org/packages/OpenCL.Net/) with C# for one small practice program before and it worked as intended. It doesn't look like it will be updated past OpenCL 1.2, though.

Anyway, it seems that C++ was the right choice for this project. I've been using a lot of the convenience features of C++11 like unique_ptrs and bounds-checking, so I rarely have to worry about manual memory management or going outside of an array. With working on a growing code-base like this one, it makes development less of a headache.

**Comment by psi29a** [comment]
:+1:   C++11 and C++14 are great!

**Comment by Ragora** [comment]
It has been making hell in debugging, though. At least here, where it seems Code::Blocks's GDB invocation can't properly deal with the pointer wrapper types. If anyone has a suggestion of an IDE that works on Linux and can properly deal with them, I'd gladly try. It preferably should also be targetable by CMake.

**Comment by psi29a** [comment]
Before, I used QtCreator for C++ then I fell in love CLion by JetBrains (makers of PyCharm).

I <3 CLion. JetBrains loves OpenSource as well. So go download CLion and give it a try and then ask JetBrain for a free license to work on OpenTESArena. :)

CLion is heavily geared towards CMake, so it is a perfect fit here.
https://www.jetbrains.com/clion/

Don't get me wrong, QtCreator is great too, you can do more than just write Qt applications. So perhaps give both a spin and see which one you prefer.

**Comment by psi29a** [comment]
For debugging my projects, I always use the combination of gdb and valgrind.  valgrind is _great_!

**Comment by Ragora** [comment]
Just as long as the autocomplete isn't terrible, the jump-to-declaration (and implementation) actually works and the visual debugger works with the pointer wrapper types in use here. None of those have ever really worked reliably for me in Code::Blocks.

**Comment by psi29a** [comment]
All you have to do is ask for two licenses for the project. The worst they can say is no. ;) If you need it, you have github host a 'webpage' for you via gpages. I've done this for my other project: 
http://world-engine.org/

I have two licenses, one FOSS license for my work on OpenMW/WildMIDI/WorldEngine/others and another paid for by my work. Obviously I switch between my work and home machines quite a bit and still work on the same projects. I wouldn't worry about it too much. They aren't going to disqualify you for working on hobbies, they see it as another way to eventually get your work to buy licenses because their employees like the product. 

I won't get into the merits of gdb, suffice it to say... visual debugger will only get you so far before you have to dig deeper. ;)

**Comment by Ragora** [comment]
It's been well more enough in pretty much all regular applications.

**Comment by psi29a** [comment]
Just trying to help. :)

I'm not saying which one is better, that is just silly... learn and use all the tools at your disposal.

I mentioned GDB because the chances are 9 out of 10 that it will already be installed on non-Windows platforms. From clued-in users who want to give a stack-trace when OpenMW dies to integration testing where you can jump right into a machine to debug why your application failed their tests or segfaulted.

Anyway, that is why I don't dismiss GDB out of hand. It has its uses, but you're right that a proper IDE is wonderful in development.

I wish you guys luck. :)

I've been using JB products for about five years now, with FOSS licenses... they've never revoked them and have been really easy going about things. That has been my experience anyway.

**Comment by Ragora** [comment]
You just need the dump file that the test created when it died to debug those sorts of situations.

So far Clion has been pretty nice, it's supporting those pointer wrappers that Code::Block's choked on but so far it doesn't seem to deal with lambdas in a way I wanted it to (I can break in lambdas, step through, but dealing with variables in it is pretty weird), but it at least is capable of showing lambda-local variables.

**Comment by psi29a** [comment]
I know what you mean, I've used Eclipse for a few years before stepping over to QtCreator (C and C++) and PyCharm (Python). 

I'll be honest, I've not had a chance to evaluate Code::Block but people seem to like it.

**Comment by Ragora** [comment]
I don't really develop much for Windows myself. :)

Code::Blocks works pretty well except for the issues I mentioned, which can be pretty infuriating.

As a thing aside, @afritz1 sorry for slightly hijacking this thread!

**Comment by afritz1** [comment]
It's okay. @kcat has sufficiently implemented OpenAL Soft and WildMIDI now, so I might as well close this issue.

**Comment by psi29a** [comment]
Man pages need to be updated, then we can make a formal release and I can start pushing downstream.

@Ragora and @afritz1 : would you like me to create an ITP for Debian (Ubuntu) to get OpenTESArena into downstream as well?  I can push it to experimental so that those adventurous enough can test and send feedback to here.

**Comment by afritz1** [comment]
I'm not familiar with what ITP (Intent-to-Package?) is for. Does it just package up this project so others on Debian and Ubuntu can work with it more easily? I don't think we need lots of people testing the project just yet. What's your opinion?

**Comment by psi29a** [comment]
You guessed it right. ITP means that I (or someone else) intends to create a package of OpenTESArena for Debian inclusion. It will go on to the mailing list, be talked about and then someone has to actually create the package. Once this is done, then it is again talked about and hopefully a sponsor (Debian Developer with more rights than I) will help champion the package for inclusion.

Once this has happened, the first release is uploaded to the Debian Lawyers can look it over to make sure it fits DFSG (Debian Free Software Guidelines)[1]. Should they OK it and it meets quality control standard, it is uploaded first to experimental. And because it requires someone else's IP (Arena itself) to play, it will go into the 'contrib' category.

I'm guessing the process can take anywhere from a month to 6 months depending on the queue size. Once it is accepted by Debian, it is then trivial for me (or others) to make updates every release. This can be anywhere between a day to a week typically.

In my opinion, having more eyes on the project is always good. It brings in more developers and testers... you can never have enough of those. Its good PR!

[1] https://en.wikipedia.org/wiki/Debian_Free_Software_Guidelines

**Comment by afritz1** [comment]
> Once this is done, then it is again talked about and hopefully a sponsor (Debian Developer with more rights than I) will help champion the package for inclusion.

Wow, that sounds pretty nifty! I guess my project might end up going farther than I had anticipated. So other open-source projects do this too, like OpenMW?

If my current MIT license causes any road bumps, I can change it to GPL, but I would like a good reason to do it first.

I like the idea of more testers, but I'm also a bit anxious about all of the questions I'd be answering for people instead of doing coding!

**Comment by psi29a** [comment]
I've done this with multiple projects already:
https://qa.debian.org/developer.php?login=psi29a@gmail.com

MIT is fine!

**Comment by afritz1** [comment]
Okay. Well, I think we should wait a bit longer until the project is free of any Arena resources being used from extracted/converted files (namely, those in my Dropbox [link](https://www.dropbox.com/s/xc8llh52eahaofs/OpenTESArena_data.zip?dl=0)). Once we start using the virtual file system exclusively to read in the floppy disk version's files, then I think there would be no legal issues at all.

What would you say the limit is on using extracted files for Arena? @kcat already mentioned this topic [here](https://github.com/afritz1/OpenTESArena/issues/7#issuecomment-225021928), and how it is "legally dubious". For example, I used a tool to extract the original font files and I assembled them into new image files. Is this something we would have to leave up to mods? I just wanted to avoid doing some things in the program that could be done outside beforehand.

**Comment by psi29a** [comment]
He's right about that, it is best to read the files in natively and convert on-the-fly to PCM and let OpenAL handle the rest. The same should be done with all other assets as well.

Best leave it up to modders for creating new content or remixing the old content. I would focus on supporting the original formats natively first.

**Comment by Ragora** [comment]
It's even more dubious if they legitimately released it with no sort of licensing terms at all. You'd have to contact them, for which they shouldn't be a loss at doing so as the worst they can say is "You can't do that" but they can't stop you from doing the above as you're not redistributing the assets.

**Comment by afritz1** [comment]
I imagine this also affects text, like character classes and locations in the game (since text is still data), so I can't use my `locations.txt`, `classes.txt`, and `artifacts.txt` files I wrote while playing the game and using WinArena. At least I can still use them as a reference, so I know what the correct information is when reading the original data. But we can't hard-code them because that's a form of redistribution.

**Comment by psi29a** [comment]
I'm going to have to pull an 'arm-chair' lawyer moment here, so please, IANAL:

Individual words nor phrases can't be copyrighted. Non-generic names can be trademarked however.
Things like: Strength, Intelligence, Armour, Stealth are things that no one cares about. However names of places referenced in Bethesda's world is starting to cross the line.

Copying sentences (full text) on the other hand is something Bethesda can go after the project for, if they wanted, and make your life difficult.

These things are best read in at runtime. It is more work, but then you don't have to worry about Bethesda sending in guys like Matt Grandstaff to ask people to stop developing.
https://wiki.openmw.org/index.php?title=Bethesda_Emails
^-- We managed to convince Bethesda that we were harmless. :)

**Comment by afritz1** [comment]
I read through most of those emails, and wow, it's pretty involved. So OpenMW has to "primarily" be on PC platforms, but it can also be on Linux, Mac, etc., as long as you don't parade around exclaiming it to everyone. It seems like having it run on Android was a big concern of theirs, too. I originally thought it didn't matter where Morrowind was played as long as the user purchased a copy legally.

**Comment by psi29a** [comment]
PC == Personal Computer, which includes Windows, Linux and OSX.

They took exception with Morrowind running on Android (Mobile/Tablet). Maybe they want to release their own version in the future? Who knows. They technically don't have a legal leg to stand on, but we worked around it. We "OpenMW Team" can't display screenshots or films of Morrowind running on Android (or Mobile Device). :)

**Comment by Ragora** [comment]
That E-Mail chain didn't help at all. The difference here is that they didn't re-release Morrowind for free while they did for Daggerfall. I so far haven't tried to look yet, but I'm pretty surprised that nobody has actually tried to figure out what their EULA terms are on the free release by now.

**Comment by kcat** [comment]
> what their EULA terms are

From their [official download](http://www.elderscrolls.com/assets/files/tes/extras/Arena106Setup.zip):
"1. You have a non-exclusive, non-transferable license and right to use this Product
for your own personal use and enjoyment. This Product is not provided for any
non-personal, commercial purpose. All rights not expressly granted to you herein
are hereby reserved by Bethesda Softworks."

But regardless of the EULA, I know the moderators over at the BethSoft forums are diligent about removing download links for ArenaSetup since it contains the CD version of the game, while Bethesda released the floppy disk version for free. Unfortunately I can't seem to find any info on UESP about what the exact differences are between the floppy disk and CD versions (some voice and video files I think, though I'm not sure which ones), but that's going to be a limiting factor for pre-converted asset distribution even if it was allowed of their free release.

**Comment by Ragora** [comment]
That is the download I checked indeed.

**Comment by psi29a** [comment]
@Ragora the email exchange was to demonstrate that bethesda does actively go out looking for these things. 

The point is, don't redistribute someone else IP. :)

**Comment by Ragora** [comment]
Of course they are, why would I think otherwise?

**Comment by psi29a** [comment]
Agreed. :)

Thread hijack complete! :P

BTW: I'm making a new release of WildMIDI today. This includes the XMI support so you guys don't have to compile from scratch anymore.

The follow up release (0.4.1) will have SF2 (soundfont) support.

**Comment by afritz1** [comment]
That's good news! (To be honest, I've just been using 0.3.9 in the meantime.)

**Comment by Ragora** [comment]
I could grab that and see what happens.
