### ISSUE TITLE
.VOC file cleanup

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#111]
Several of Arena's .VOC files are low quality and contain clicks and/or pops, so they're not the most entertaining sounds to listen to. WinArena does some cleanup by removing certain samples, but it's mostly hardcoded to Arena's files, so it doesn't seem like the best solution (see `ArenaLoader::LoadSound()` in WinArena's [ParseBSA.cpp](https://github.com/pralinor/opentesarenapp/blob/4b6d097d7c40352c62f9f95068e89df44e323832/WinArena/ParseBSA.cpp#L680)).

@kcat, is there a better way to remove clicks and pops from 8-bit PCM data? I realize this question might lead into sampling theory and a much bigger solution than I was expecting, so if there isn't a simple solution, then maybe the hardcoded way will suffice.

**Comment by kcat** [comment]
> @kcat, is there a better way to remove clicks and pops from 8-bit PCM data?

Not really, unfortunately. It would require much deeper analyzing of what the sound is, detecting and cleaning up abnormalities that don't fit what's expected, and I'm not aware of any projects that do it (at least in a way that works for the general case and doesn't risk messing up sounds itself).

Does the original game exhibit clicks and pops when playing those sounds? If not it could be a parsing issue, or if it does it may not be practical to try to fix in the engine (manually fixed sounds could be provided as a mod).

**Comment by afritz1** [comment]
The popping plays consistently for some sounds, especially weapon swings, where it's audible at the beginning every time (which is fairly annoying until you get used to it). I don't think Arena makes any modifications to the .VOC files it loads. I think it concatenates the .VOC files for speech, though, but even then it's not always a smooth transition in the original game.

The WinArena author mentions that there is a pop near the end of one particular sound (`VAMPIRE.VOC`), but truncating it might take too much off, so it looks like this is going to require some give-and-take for certain sounds. But like you mentioned, maybe that's something to leave up to mods (otherwise it's just going to be a list of special cases in the .VOC loader).

**Comment by Allofich** [comment]
> Does the original game exhibit clicks and pops when playing those sounds?

I'm attaching recordings I just made of swinging a weapon in both the original game (using Dosbox-X) and OpenTESArena, so you can compare them yourself for this sound.

When I listen to them I can hear the pop sound in the original as well. Although the DosBox configuration settings might matter here, the sound from the original game is more muffled, and I think this may take away some of the harshness of the pop as heard in OpenTESArena's playback of the sound.

> I think it concatenates the .VOC files for speech, though, but even then it's not always a smooth transition in the original game.

The only concatenated speech I can think of is the speech in the CD version for the cutscenes. Is that what you mean?

[Swing sounds.zip](https://github.com/afritz1/OpenTESArena/files/1751427/Swing.sounds.zip)

**Comment by Carmina16** [comment]
It seems the clicking sound is a small negative DC artifact in the beginning. It should be quite simple to detect and mute.

**Comment by kcat** [comment]
> When I listen to them I can hear the pop sound in the original as well. Although the DosBox configuration settings might matter here, the sound from the original game is more muffled, and I think this may take away some of the harshness of the pop as heard in OpenTESArena's playback of the sound.

Sounds like a difference in the resampling quality. An impulse sound like the clicks and pops in these VOCs generally cover a good bit of the frequency spectrum, but is limited by the nyquist frequency of the recording (that is, presuming these sounds are 11khz sample rate, the clicks and pops can only reach up to about 5khz, i.e. half the sample rate).

The original game likely did its mixing at the same rate as the sounds to avoid having to resample, so the hardware was able to play it without much noise above 5khz. DOSBox, since it's emulating older hardware capabilities, presents an audio stream buffer to the application for the expected 11khz output rate, which the system resamples for its mix to the real output. The system usually uses a fairly high quality resampler since it doesn't resample many sounds at once. This helps prevent much noise from occurring above 5klhz, leaving the clicks and pops to sound muffled and dulled.

OpenAL, in contrast, mixes directly to what more modern systems are outputting, like 44.1khz or 48khz (or possibly higher) sample rates to avoid multiple resampling passes. By default, it also uses a rather low quality resampler (like linear) since it's potentially resampling dozens or hundreds of sounds simultaneously. That results in notably more noise above the 5klhz input limit, creating "brighter" clicks and pops.

OpenAL Soft provides ways to use a better resampler, either via the alsoft-config utility or the [`AL_SOFT_source_resampler`](http://openal-soft.org/openal-extensions/SOFT_source_resampler.txt) extension. Both of those options should help make the output sound cleaner, like it was with the original.

> It seems the clicking sound is a small negative DC artifact in the beginning. It should be quite simple to detect and mute.

Possibly, though that would only help for sounds that have it at the very start. I'd say it's not really worth it since it's extra processing needed to load each sound, and it can be fixed by modifying the files themselves via mods. Who knows, some people may even want the clicks and pops in there as it reminds them of playing the original when they were younger.

**Comment by afritz1** [comment]
> Allofich said: The only concatenated speech I can think of is the speech in the CD version for the cutscenes. Is that what you mean?

Yes. My guess is that the game simply takes the beginning of the next speech file (i.e., `1294_00B.VOC`) and pastes it onto the end of the previous speech file (i.e., `1294_00A.VOC`). I experimented with those files a little bit and OpenTESArena can load them and play them one after another just fine. I need to check Jagar Tharn's final speech, though, since Audacity shows `1447_00A.VOC` having 9708hz and `1447_00B.VOC` having 11111hz.

I think @kcat is right about the difference in sound between the two files you attached. The OpenTESArena one sounds more clear (I guess?), because of differences in resampling between OpenAL Soft and DOSBox, but that might not necessarily be "better" in this context.

> kcat said: Who knows, some people may even want the clicks and pops in there as it reminds them of playing the original when they were younger.

I think the engine should leave the sounds as they are then. I might tinker with the resampling a little bit just to see what it can sound like, though. On another note, this reminds me of the music for Dwarf Fortress. I think it was intentionally recorded at a lower quality so it would have a more wistful feel to it, so I see what you mean there.

**Comment by afritz1** [comment]
See commit 2382208d802ff0eaf165d13d6ab4253856296cee. I upgraded OpenAL Soft to version 1.18.2 and the audio manager is using the source resampler extensions now, although this seems to have broken Travis CI on Linux and macOS (because they either don't have `alext.h` or they aren't at 1.18.2 yet?).

**Comment by kcat** [comment]
> although this seems to have broken Travis CI on Linux and macOS (because they either don't have alext.h or they aren't at 1.18.2 yet?).

You can either copy the extension's declarations from `alext.h` into your own code, or copy the whole of `alext.h` (and `efx.h`, which it relies on) into your repo, so you don't have to rely on it being with the system.

Regarding that commit, you should check that the `AL_SOFT_source_resampler` extension exists, and avoid using those new properties if it doesn't. Something like:
```
// Store this in the audio manager, to avoid checking for the extension multiple times
bool mHasResamplerExt;
...
// After the context is set...
mHasResamplerExt = alIsExtensionPresent("AL_SOFT_source_resampler");
...
// When setting up a source
if(mHasResamplerExt)
	alSourcei(source, AL_SOURCE_RESAMPLER_SOFT, mResampler);
```

**Comment by afritz1** [comment]
Closing for now, since the user can now change resampling options in commit aef655d2de125daa8fbc1898ebf1e31bba47bce3, and .VOC files probably aren't going to be further manipulated by the engine any time soon.
