### ISSUE TITLE
Remembering travel destination selection

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#116]
Happy to see the progress on fast travel!

I noticed a minor feature in the original game currently missing in OpenTESArena. If you select a location, the original game will remember it and keep the flashing boundary for it even if you exit out from that province's view or open the view of another province. It remembers it until you initiate a travel or exit back to the 3d game world.

**Comment by afritz1** [comment]
I noticed this in the original game too. I thought it might be too small of a feature to worry about, but maybe I could add it anyway. With the current data lifetimes design, it might take the form of a nullable (int, int) pair passed between the active `ProvinceMapPanel` and `WorldMapPanel` to point to the selected province and location ID.

Arena probably has longer lifetimes for its data (mostly in global scope as extern variables/arrays, I imagine), so since the design between the two engines is a little different, some features may be easier or harder to implement depending on the details of each. I mention this because, as it stands, when the player goes from the province map to the world map in OpenTESArena, all of the province map's variables are destroyed, so I need to give the selected location data a "promoted" lifetime so to speak (i.e., by making it a WorldMapPanel/ProvinceMapPanel constructor parameter or giving it to the GameData object). I could easily just make all panels have global lifetimes, but then I wouldn't have as strong of guarantees on data lifetimes that I do now (there'd be a lot more variables in garbage states).

Anyway, maybe I'll document the whole design at some point once it's a bit more stabilized. The ups and downs of this design are one thing I have to deal with from rolling my own UI code (don't do it if you can avoid it!). I don't know why, but UI programming just seems _so_ much harder to do quickly than other stuff. Probably because there are a lot of variables involved.

**Comment by afritz1** [comment]
See commit 22f2cbc3c6d22db90e39317df4adce5ca46257cb.

**Comment by afritz1** [comment]
I noticed that the original game lets you click the travel button even if you're looking at a province that doesn't have your selected location. This is kind of getting into the territory of undesirable features, because I'm trying to see things through the original developers' perspectives, and this is probably just something they forgot to have a condition for (so therefore I think it falls into the category of unintentional behavior).

**Comment by afritz1** [comment]
I wasn't happy with the change only matching the original game halfway, so now the fast travel memory matches the original behavior in commit 47d2716f032dbeac0767cac663d1ee20ca105f52.

**Comment by Allofich** [comment]
Works well!
