### ISSUE TITLE
DEMO.MIF from the Arena demo loads in retail Arena but not OpenTESArena

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#119]
Tested by taking DEMO.MIF and DEMO.INF from the Arena demo and putting them in the retail folder, with DEMO.MIF renamed to START.MIF.

Retail Arena (ver 1.06) loads the level, but in OpenTESArena the program crashes with
`[Assets/MIFFILE.cpp(177)] Error: Unrecognized .MIF tag "STOR".`

I don't know if it's in your scope to support the demo level, but it would be fun to be able to support it, and the original game can load it.

**Comment by Allofich** [comment]
In case you don't have it, the demo is available on the UESP.
http://en.uesp.net/wiki/Arena:Files

**Comment by Carmina16** [comment]
Unknown data in a chunked file is not an error anyway.

**Comment by afritz1** [comment]
See commit c0e84bacee2cc42fa061c4dd0256cb32c4a2af96. It was an easy fix (not sure what to do with `STOR` data, though).

And @Carmina16, you're right about that. I just didn't want to let unimplemented sections slide by (otherwise it'd be a silent error and I'd wonder why something wasn't showing up in-game).

**Comment by afritz1** [comment]
Fixed the `std::stoi` problem in commit b6bba31c3554eea0477c5212b01849065b6e867f. It's because the .INF file was being decrypted even though it was plain text.
