### ISSUE TITLE
Palace variants

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#137]
I noticed this todo in `CityDataFile.cpp`:

```
			// @todo: city-states have five palace variants, right? Should the modulo
			// be 3 or 5 depending on the city type?
```

I tried in original Arena and visited the palaces of all the city-states in Hammerfell, but all were 1 through 3.

```
 PALACE1
 Taneth
 Dragonstar
 
 PALACE2
 Rihad
 Sentinel
 Skaven
 
 PALACE3
 Gilane
 Elinhir
 Hegathe
```

Just in case it was a Hammerfell thing, I tried a few in Skyrim

```
PALACE1
Snowhawk
Riften

PALACE3
Falcrenth
```

By this point I feel pretty confident to say that original Arena (this is the floppy version) only uses 1 through 3 for the city-state palaces.

Does the current code produce the above results?

**Comment by afritz1** [comment]
It appears PALACE4.MIF and PALACE5.MIF are duplicates of PALACE2.MIF and PALACE3.MIF. Were you able to determine that the instances of PALACE2 and PALACE3 you found were actually using their respective .MIF files? I'd agree that the game only uses city palaces 1-3, but I can't tell with certainty yet if that modulo should be 3 or 5 because palaces 4 and 5 look identical (right?).

Palace entrances aren't working yet, and I'm not sure if I'd be able to obtain the correct information by sampling the blocks in their current state to see what their .MIF file would be.

**Comment by Carmina16** [comment]
Yes, it is 3 explicitly.

**Comment by afritz1** [comment]
Thanks. It should be correct now in commit 2acd1dd123254018bf74fa3b531bd50f4e98f3f7. I haven't checked it in-depth yet since I'm focusing on revisions for TEMPLATE.DAT parsing.

I think the reason why 4 and 5 aren't used is because they don't have impassable blocks around the perimeter of the level, so the player could in theory use Passwall to go into infinite nothingness.

**Comment by afritz1** [comment]
@Carmina16, do you know anything more about the palace gate algorithm? The one for changing blocks to the proper type? If I remember correctly, you mentioned that it was difficult to understand.

**Comment by Carmina16** [comment]
The table (here)[https://github.com/afritz1/OpenTESArena/issues/91#issuecomment-354220353] is accurate. The code checks for grate blocks around the "palace" blocks to find out the gate orientation, but you, of course, can use something else as it produces the indicated result.

**Comment by Carmina16** [comment]
The MIF name is dependent on the city type, and the variant in calculated as described [here](https://github.com/afritz1/OpenTESArena/wiki/Interiors#interior-variants).

**Comment by afritz1** [comment]
Palaces and their gates now have the correct orientation in commit ae392a6883eb4ce437d36079f83bd676ae32c3ed. I will get to the .MIF filename and entrance behavior tomorrow hopefully.

**Comment by afritz1** [comment]
The palace entrances and graphics are now correct in commit 3d9847653dc6f54282f3579aec8156821b35f7f1 (and the original reason this issue was opened is also done), so this issue can be closed.
