### ISSUE TITLE
Other open-source project to check

### ISSUE THREAD

**Issue by Nodepad** [afritz1/OpenTESArena#138]
Hello, several years ago I was working on translation of TES: Arena and make two open-source libraries based on my findings. Most of the stuff is already implemented here. But I thought you'll be interested in LZSS-based and DEFLATE-like algorithms of image compression (I couldn't find it in this repo) and text relocation table of EXE file v.1.6. Also I could find some of my ASM listings of executable v.1.6 if you're interested.

[TESA EXE Translator](https://github.com/Nodepad/python-tes-arena-exe-translator)
[TESA Resource Lib](https://github.com/Nodepad/python-tes-arena-resource-lib)

**Comment by afritz1** [comment]
Thanks for stopping by. It's interesting that you have several algorithms for reading Arena's data. I wonder how many other people out there have also done similar work? (at least a few I know of, like for WinArena, BSATool, etc.).

I believe my engine is able to load all of Arena's image formats now, so the image decompression methods should be fine as they are. The person who implemented support for type 8 images did leave a comment [here](https://github.com/afritz1/OpenTESArena/blob/f825d5c229f0ff2d2d9cb0f81c9341baad5ee43b/OpenTESArena/src/Assets/Compression.h#L179) though about it seeming like a DEFLATE algorithm.

So the text relocation table is for translating the text in the executable to another language? I saw in your EXE translator project that it reads the text then sends it out to an XML file where it's then translated and put back into the executable? Is that right? My [ExeData](https://github.com/afritz1/OpenTESArena/blob/f825d5c229f0ff2d2d9cb0f81c9341baad5ee43b/OpenTESArena/src/Assets/ExeData.h#L19) class is essentially the same as your `exe.xml` file; it reads in most of A.EXE's text and constant data into memory at runtime. I make sure to do it this way so I don't distribute any of Bethesda's intellectual property in releases. I still need to add support for the CD version's executable.

By ASM listings, do you mean decompiled code? I tried looking into it a couple years ago with a decompiler but it was mostly gibberish and I couldn't make any sense of it. Since then I've been following clean-room implementations with other people and just trying to load Arena's data "the right way" when implementing features. Again, that's mostly to avoid IP issues.

**Comment by Nodepad** [comment]
Thanks for pointing out on algorithm implementation. I've missed it because was looking into `Compression.cpp`.

About EXE translator, I've created a patch which allows to draw fonts in range of 0x21-0xFF instead of 0x21-0x7F, which helped me with translation. The `exe.xml` contains strings and pointers to them, so it allows me to relocate all strings within executable and change their length.

Yeah, I've some decompiled and decrypted code, which helped me with translation. Maybe the main thing you could be interested in is player struct description which is used in save files.

**Comment by afritz1** [comment]
The save data implementation is partially complete, and much of the current progress is thanks to @Carmina16's documentation work in the [wiki](https://github.com/afritz1/OpenTESArena/wiki/Save-File-Formats). There's a treasure trove of information in there and I'm working through implementing each piece of it as I have time. If you think anything in the save data formats (or anywhere else you're interested in looking) is incorrect or out of place, feel free to mention it here and I'll revise it.

**Comment by Nodepad** [comment]
**INVENTORYITEM**
```
...
BYTE Hands; // Also # of charges left (could be wrong because there is `Health` field)
...
WORD Health; // Also amount of money left for King Orgnum's coffer
WORD MaxHealth; // Also # of max charges
DWORD Price; // Repair cost * Repair time is related to this field.
...
```

**Comment by afritz1** [comment]
Thank you for adding these here. I'll try to get to them soon. I've been distracted with my renderer improvements for the past few days.

**Comment by afritz1** [comment]
Looks like this issue can be closed.
