### ISSUE TITLE
Overly verbose type casting and pointer checks

### ISSUE THREAD

**Issue by kcat** [afritz1/OpenTESArena#14]
The code seems to be littered with constructs like
```auto var = type();```
and
```auto var = static_cast<type>(value);```
These serve no functional or practical benefit, and actually just result in obfuscating what's going on (and in some cases, can actually impact performance since it's constructing a temporary of the given object type then copy-constructing the real object with it, rather than constructing the object in-place). The same thing can be written as
```type var;```
and
```type var = value;``` or ```type var{value};```
which is just as type-safe, and is more clear, with what it's doing, along with being shorter.

I'm not suggesting to go through and change them all right away, but I would suggest changing them as you work on code around where they appear.

I've also noticed a number of redundant pointer checks, where you ```new``` an object into a unique_ptr container, then assert that the unique_ptr has a non-null pointer. By default, ```new``` will never give back a null pointer and will only fail by throwing an exception, so the pointer is never set. It can give back null if you use ```new(nothrow) type```, but that's not (and generally shouldn't be) used. Again, I'm not suggesting to go through and change it right away, but I would suggest removing such checks as you work on code around where they appear.

**Comment by afritz1** [comment]
I have been preferring the verbose syntax since the `type var;` syntax just looks like it's doing nothing (when it's actually calling the default constructor), but I will consider using your suggested syntax now.

I also found out recently that I can't return a reference of a cast operation on a member, like:

`const int &getValue() const
{
    return static_cast<int>(this->some_size_t);
}`

won't work because it's the result of an expression. I'll be turning those `const &` return types to values as suggested by @Ragora in issue #4.

Doing the (unnecessary) assert checks is just my way of doing a kind of post-condition for a method, so I can easily determine what the intended status is for the variables at that point. Some variables I like to leave null in a constructor because they aren't used until later (maybe that's a poor choice, though).

I'm not extremely familiar with C++ exceptions so it's news to me that `new` doesn't return a nullptr. I don't really use `nothrow` at all yet.

I will keep this issue in mind as I work now, thanks.
