### ISSUE TITLE
Sun rising/setting times

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#140]
The sun in original Arena starts rising from the horizon at 6:00 AM. (actually first visible at 6:03 AM, see below) and finishes setting below the horizon at 6:00 PM. In OpenTESArena it does so at 5:30 AM and 6:30 PM.

(The sun in original Arena actually first appeared when rising when I checked at 6:03 AM game time. The Arena sun seems to move once every 3 game minutes (sometimes 2 I think), so I think that's why it first became visible at 6:03 AM, having finished its first move.)

**Comment by afritz1** [comment]
It appears to be because of differences in the position of the rendered sun relative to where `sunDirection` points. Currently the bottom of the sun is `sunDirection`; it's the same as mountains for convenience, although since you brought it up, it should probably be different.

https://github.com/afritz1/OpenTESArena/blob/034ba9575653f5b9603f17e3e097c3d99c19f21d/OpenTESArena/src/Rendering/SoftwareRenderer.cpp#L1136

**Comment by afritz1** [comment]
Fixed in commit 76c7ba44aa3548bf0ab680562a3ed1c72ef873fd.

I'm not worried about the small 3 minute difference. I think it's splitting hairs at that point. Feels like the original game does a truncation when projecting the angle, or it's just not precise enough or something, so the Y pixel value isn't high enough to be visible until the angle is sufficiently large.

**Comment by Allofich** [comment]
I agree, the original game probably starts from 6 AM and just doesn't show at first because of the way it moves.
