### ISSUE TITLE
I can't get music to work in debian

### ISSUE THREAD

**Issue by pxsxs** [afritz1/OpenTESArena#203]
I downloaded the eawpats folder and put it inside data/ but I can't hear the music.
the log shows the following:

```
[Media/AudioManager.cpp(590)] Warning: Failed to play PERCNTRO.XMI.
[Media/AudioManager.cpp(590)] Warning: Failed to play EVLINTRO.XMI.
[Media/AudioManager.cpp(590)] Warning: Failed to play SHEET.XMI.
[Media/AudioManager.cpp(590)] Warning: Failed to play PERCNTRO.XMI.
```

**Comment by afritz1** [comment]
I don't think the Linux release was compiled with WildMIDI. I made the release but I don't know enough about shared libraries to make it work for everyone.

**Comment by afritz1** [comment]
The 0.14.0 Linux x86-64 release was compiled with WildMIDI 0.4.3 on WSL (Windows Subsystem for Linux) and it works on my Debian laptop. I'm going to assume this issue is resolved. It came down to me just needing to learn how to get the libwildmidi .so file from the libs folder. If there are any new issues then I'll reopen this or make a new issue.
