### ISSUE TITLE
Sometimes the Player Classes Load

### ISSUE THREAD

**Issue by Ragora** [afritz1/OpenTESArena#5]
I've been fighting this a lot. The player classes dialog will sometimes show up with no classes to select, this includes if you navigate back (hitting escape) and going back to new game when it already worked.

**Comment by afritz1** [comment]
I ran through the character creation back and forth a few times to stress test it and the class list is working fine every time for me. Your problem is happening on the "Choose thy class..." screen, right?

The code for getting the list of classes from "data/text/classes.txt" is run whenever the `ChooseClassPanel` constructor is run, which is just before the "Choose thy class..." screen appears. This assertion `assert(this->charClasses.size() > 0)` at the end of the constructor makes sure that the classes were loaded from file.

Maybe it's a problem with the ListBox class, but I'm not sure about that. I can't seem to reproduce the problem.

**Comment by Ragora** [comment]
It happens more often than not: https://i.imgur.com/x20AwBI.png

**Comment by Ragora** [comment]
Was caused by the scroll index of the ListBox not being initialized to some sane value when constructed. I don't know why it wouldn't have manifested on Windows (either MSVC initializes values to something sane for you or the memory is zero'd out when allocated on Windows).
