### ISSUE TITLE
Extracting data from A.EXE

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#51]
There are several useful strings in the A.EXE file, but they cannot be read in at runtime directly because the executable is compressed with PKLite v1.12. There are tools like UNP and The Executables' Unpacker which can uncompress A.EXE into a readable state, but they are DOS programs and their source code is either unavailable or in assembly.

Some options that have been discussed:
1. Distribute DOSBox and the UNP executable with OpenTESArena.
2. Write a PKLite decompressor using code from the disassembled UNP executable.

**Comment by wheybags** [comment]
http://unp.bencastricum.nl/unp4-src.zip ?
It's assembly, but still a hell of a lot better than disassembling.

**Comment by afritz1** [comment]
Yeah, that's the UNP source code assembly I was referring to. One of the members on the OpenMW IRC (capitol) looked it over and suggested using either that or the disassembly.

**Comment by afritz1** [comment]
I added a simple skeleton for the decompressor in a new ExeUnpacker class. It's in the `src/Assets` folder.

If anyone would like to try their hand at a C or C++ implementation for this, just experiment with some of the assembly files from @wheybags' link (http://unp.bencastricum.nl/unp4-src.zip) and open a pull request for [ExeUnpacker.cpp](https://github.com/afritz1/OpenTESArena/blob/master/OpenTESArena/src/Assets/ExeUnpacker.cpp) once you have any interesting changes to add. Again, it's for PKLITE v1.12, the compression used with A.EXE for Arena.

You'll know the decompression worked if the file data has several readable strings in it. You can use the results from running UNP.EXE (from http://unp.bencastricum.nl/unp411.zip) on A.EXE as a reference (I ran it in DOSBox).

**Comment by Yt-trium** [comment]
I was just searching to help a little by reading some UNP code, and here are my result : 
We can assume that the program use a [load -> patch-> trace -> dump] strategy (i'm not an expert in old-school 16 bit assembly).
So, after all, UNP isn't very interesting for us, because we don't care about the A.EXE (unpacked) file to run on dos, we just want to dynamically extract the string from the packed file, and after all, any other dump of A.EXE will work for us.

We still have these solutions : 
- Make a 16 bit pe debugger to dump A.EXE.
- Recreate the PKLite 1.12 decompression algorithm, from the A.EXE (packed) file, and try to run it directly over the complete file (maybe we will got those string).

**Comment by Ragora** [comment]
The latter is the easier option, though the former could be accomplished with a minimal implementation of an interpreter to execute it until decompression is complete. Don't think you'd need a full DOS environment to get the decompressor in its original form to work.

**Comment by Yt-trium** [comment]
After a little discussion with the creator of X-TRACT (another UNP like unpacker)  the best way (in our case) is to debug A.EXE and try to recreate the unpacking code from it.
I found a dos-box with debugger, you can get it here : http://www.vogons.org/viewtopic.php?t=7323
Maybe it will help someone a little...

**Comment by afritz1** [comment]
I've been playing around a little bit with the DOSBox debugger. It's kind of fun actually. I really like that it prints out any files being opened by A.EXE, so I can see exactly which textures are being used in the interface, etc..

I could see this tool really helping out sometime. It's more informative than I thought it would be. I'd like to get other parts of the foundation done first before I focus on the decompression code though, but this will definitely be a starting point for seeing how A.EXE unpacks itself.

**Comment by Dozayon** [comment]
I have managed to clone the decompression subroutine from A.EXE in C code. It can decompress all of the data stored, but it is very rough and difficult to understand at the moment. I can't show it to you since it contains copyrighted code, but I could rewrite it in C++ in a more abstract way (removing copyrighted code), so then I could distribute it. Or I could write a specification for the compression format. Which one do you think would be better?

**Comment by afritz1** [comment]
That's great news! Well, the easy way would be to rewrite it in another way (like with C++), but the "right" way would be to have another developer like myself follow a specification and implement it independently. Besides, I might learn a thing or two if I participate in some coding. Once that's done, we'll be able to pull strings from A.EXE at runtime.

**Comment by Dozayon** [comment]
I have finished writing the specification for the PKLITE V1.12 compression format. You can see it at #61. I hope it isn't too difficult to understand. Please make changes to it if you think they will make it more readable or understandable. Please also let me know if you have trouble implementing the specification in code.

**Comment by afritz1** [comment]
What a well-written specification! I'm able to make sense out of most of it. It might be of some use to other curious folks sometime, too, and it could even make it onto the [UESP](http://en.uesp.net/wiki/Arena:Arena).

No worries about the pointer relocation. Right now I'm mostly concerned with getting the strings of names and phrases in the executable, and maybe some structs of certain data later on.

**Comment by Dozayon** [comment]
Thank you for your kind words.

If you try implementing the specification, but it doesn't produce the right data, then please show me the code with the implementation. I'll try to amend the specification to correct the issue, or make it clearer on how to implement it correctly.

I've had a lot of fun analyzing the code and writing the specification, so if there is any other format/structure/procedure you want me to analyze, please ask.

**Comment by afritz1** [comment]
Finished in commit d3980d4ad026e48188564be207999ef8e1818da2. I can see some relevant strings in the output, so the unpacker should be correct then. Thanks a lot for writing the specification, @Dozayon!

**Comment by NY00123** [comment]
So P4R4D0X pointed me to this issue (back when it was open). I think that I'll want to ask someone (probably @Dozayon ) a few questions about the decompression mechanism. Not in this issue, though.

Admittedly, I'm not that familiar with the series of The Elder Scrolls, but I'm sure there's been a ton of work into OpenTESArena! Even just all the research leading to the above specification for the PKLITE V1.12 compression format must be impressive.

So to summarize, I've gotten a weird (and somewhat low-priority) use-case for ExeUnpacker: Decompressing KDREAMS.EXE from Keen Dreams v1.00. The purpose of this is making refkeen (https://github.com/NY00123/refkeen) usable with the original data for DOS. Currently it expects the EXE to be unpacked. EXEs of later versions of Keen Dreams should be LZEXE-packed, which is supported by refkeen.

I've gotten a (relatively minor) modification of your ExeUnpacker.cpp more-or-less working with such an EXE. Although my codebase is in C99, the (modified) unpacker is still coded in C++ for now.

It does look like the Keen Dreams v1.00 EXEs were packed with an older version of PKLITE. Main differences from A.EXE:
- The compressed data begins at offset 800 (320h), rather than 752 (2F0h) as applying to A.EXE.
- The check that the last word is 0xFFFF *will* fail, so it's disabled in my modified unpacker.
- decompLen actually gets the *wrong* length (too long), but luckily the length is already known in my case (the packed KDREAMS.EXE's size and crc32 are checked before decompression).
- Instead of going through that "Decryption" mode, you simply read-and-write bytes as-is.

I'm wondering what name should I give to to the unpacker in refkeen, if any. "unpklite" somehow doesn't sound as good as "unlzexe" to me, but this may just be a personal opinion.

Thanks again for all of your work on OpenTESArena, including the EXE unpacker!

**Comment by afritz1** [comment]
Hi NY00123. It's nice to hear that others are also finding uses for our code! I usually write a lot of comments in complicated systems like the EXE unpacker so I can still make sense of it a few months later.

Frankly, I'm shocked that we were able to get the unpacker working for A.EXE so quickly. Dozayon and I used the "clean room" design so we would avoid using any proprietary code. My implementation is a *very* rough draft that makes a lot of heap allocations, but it works, and that's what matters. There's relatively little documentation about Arena, so again I am surprised with where we are at with file format decoding.

I haven't been hanging out with the DOS games community for very long, but it's nice to see what other people are still doing to keep the classics compatible with modern computers!

**Comment by NY00123** [comment]
Hey afritz1, it's great to read your feedback! And yeah, it's been relatively quick... just a few months! I read about the "clean room" design above.

As I plan to port your implementation to C (with possible minor adjustments for KDreams), there might be less heap allocations, but we'll see.

This topic has made P4R4D0X and me look again for a specific version of PKLITE, just in a weird attempt of mine to recreate the Keen Dreams v1.00 EXE, byte-by-byte. We've figured this out:
- P4R4D0X found a PKLITE EXE unpacker named dislite. However, it seems to basically call the decompressor stub within the packed EXE, and thus isn't portable to other platforms. Link: https://johnpc.home.xs4all.nl/dislite/
- A version of PKLITE, marked "1.00c" but really is v1.00 beta, has been found...somewhere. Unfortunately I'm not that sure I should link to the place, though. (It also requires some kind of a login, but it's not that difficult to find it.)
- Finally, I've found out PKLITE v1.05, which really appears to be the one originally used for KDreams v1.00: http://cd.textfiles.com/phoenix2/02a/

So, to conclude: Looks like PKLITE v1.05 was used for Keen Dreams v1.00, compared to PKLITE v1.12 as used for TES Arena.

**Comment by NY00123** [comment]
Just adding that dislite's "COPYING" terms appear to be quite restrictive, basically allowing the distribution of the program and the included documentation in their original forms only. It is not allowed to sell copies of the program.

Thus, it's safer that I won't use this program's code as a base for anything.

**Comment by NY00123** [comment]
I've imported the modified ExeUnpacker to reflection-kdreams, and finally ported it to C.

For the interested, a summary of all related commits may currently be found here: https://github.com/NY00123/refkeen/commits/master

Initial import: https://github.com/NY00123/refkeen/commit/c4414550f95b40b8b6655e21a2b1d053c2c1a4af
Last related commit (fix for a silly issue): https://github.com/NY00123/refkeen/commit/1e91325fc95c3fbef61851d6f78030ffbd1d2f2e

I should also tell, that I've tried to (privately) get in contact with one of you, asking a few questions (since I don't really want to further spam this OpenTESArena issue).

Admittedly, these were maybe a bit overwhelming, so I'll just leave this for all of you, for now:

Does anybody think I should use a name other than "ExeUnpacker" in reflection-keen? If so, any suggestion? (Reason is that it may sound a bit generic, and unlzexe is already in there.)

**Comment by afritz1** [comment]
It looks like you were able to port it! Thanks for showing credit, too :). Again, it was a rough draft of mine, and someone else with a better understanding could probably improve on it.

I thought ExeUnpacker was kind of a generic name when I made it up, too. Maybe something else like PkliteUnpacker would be better? Or PkliteUnzip?

You can reach one of us on the project's [freenode channel](https://webchat.freenode.net/) (#opentesarena). I haven't set up a project email yet, and I don't want my personal email to get bombarded, so I've just been using GitHub's issues and the IRC chat for now.

**Comment by NY00123** [comment]
Hey there,

Thanks for your interest! Obviously, I didn't want to change the behaviors more than required for unpacking KDREAMS.EXE, but there were also a few other changes, like making these binary trees hardcoded into the EXE (although it's maybe bit less reliable in terms of long-term maintenance), and modifying BitTree_get (BitTree::get) to accept the equivalent of the GetNextBit lambda.

I've eventually (separately) gotten in contact with one of the users here (@Dozayon to be specific). All that I think I'll mention from there (which is somewhat relevant for my preceding post) is the suggestion of the name "unPaKaLITE".

I'm still not entirely sure about the unpacker name, heh. While "PkliteUnpacker" is the best choice out of the few I've heard so far, it seems to be used by the following GPLed code (not sure what's this, maybe some x86 code interpreter and/or translated x86 code?) - https://github.com/uxmal/reko/blob/master/src/ImageLoaders/MzExe/PkLiteUnpacker.cs

Should probably not use "unpklite", too, as it turns out this is already in use by some old DOS program.

I've just come up with another possible choice of a name: "depklite" (which seems to be more-or-less unused, according to Google).

I've considered looking for someone at IRC, but following the above contact and a bit more research of mine, maybe I'll manage anyway. Thanks for offering the option, though.

**Comment by NY00123** [comment]
OK, I think it's finally time for another report (hopefully won't add much more than this), albeit a bit belated.

To begin with, I've renamed the C port of ExeUnpacker to depklite, and also prepared and uploaded another release of Reflection Keen. It now supports Keen Dreams v1.00. This includes the ability to transparently unpack the EXEs as required, thanks to ExeUnpacker/depklite!

Next, here's an explanation for my email to @Dozayon (other than suggesting another name for the unpacker). Basically, there's a collection of tools named "CKPatch", which can be used to patch-and-execute 16-bit real mode DOS executables, without modifying the actual EXE files (only in-memory copies are touched).

Note that only a small set of EXEs is supported. This includes a few Monster Bash EXEs, although until recently, they had to be manually unpacked with UNP 4.11 or some other tool (PKLITE might do the job). Reason is, they were originally packed with PKLITE v1.15, unlike other EXEs being packed with LZEXE v0.91 (or possibly not packed at all).

CKPatch has supported unpacking LZEXE-packed EXEs on-the-fly, by running the decompressor stub present in such an EXE. The decompressor had to be patched so it jumps back to CKPatch, rather than to the starting point of the unpacked EXE. The unpacked EXE's stack location is also patched (albeit this might be a bit redundant). There's no other modification to the decompressor stub.

As it turns out (shouldn't really be a surprise), with very few changes, the same can be done to the PKLITE-packed Monster Bash EXEs. Main reason, obviously, is that the CKPatch code doesn't really contain actual decompression code; It simply executes what's found in the packed EXE, after applying minor changes.

I did have to figure out how a few things work, along with a way to tell PKLITE v1.15-packed EXEs apart from other EXEs. Here were my conclusions:
- Originally, for LZEXE-packed EXEs, CKPatch simply looked for a specific occurrence of the "LZ91" string in the packed EXE. This is also the approach used by UNLZEXE 0.7.
- However, I found out this fails for the Keen 6 v1.5 EXEs, in which the string had been replaced with NUL bytes. So I imported UNLZEXE 0.8's approach of comparing the decompressor stub's first 232 bytes against a known signature.
- I then decided to settle for an almost-identical solution for the PKLITE v1.15 packed EXEs. It's a check of the decompressor stub's first 72 bytes, except for the very first 6 bytes, which are ignored.

Thanks again for your work on ExeUnpacker! I suppose it wasn't that necessary for the CKPatch work, but it must've inspired me to do this (and even more than beforehand)!
Well, OK, @Dozayon did offer me two possible ways for modifying the decompressor stub. As expected, one of them is more-or-less what's already been done for LZEXE-packed EXEs.
