### ISSUE TITLE
terminate called after throwing

### ISSUE THREAD

**Issue by Translator5** [afritz1/OpenTESArena#57]
```
XXX@XXX ~/XXX/OpenTESArena-master/build $ ./TESArenaGame: Initializing (Platform: Linux).
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 0) >= this->size() (which is 0)
Abgebrochen
XXX@XXX ~/XXX/OpenTESArena-master/build $ ^C
```

Linux Mint 18 - 64bit

The x-executable do not start :/

**Comment by afritz1** [comment]
Hi Translator5,

The debug message `Game: Initializing (Platform: Linux)` tells me it's stopping somewhere around here in [Game.cpp](https://github.com/afritz1/OpenTESArena/blob/a3d9b7379728a5d5bf35000d9a0e9b3a7fc4c013/OpenTESArena/src/Game/Game.cpp#L31):

```C++
Game::Game()
{
    Debug::mention("Game", "Initializing (Platform: " +
        std::string(SDL_GetPlatform()) + ").");

    // Load options from file.
    this->options = OptionsParser::parse();

    // Initialize virtual file system using the Arena path in the options file.
    VFS::Manager::get().initialize(std::string(this->options->getArenaPath()));

    ...
```

Since it doesn't get to the audio manager initialization, that narrows it down to the options parsing or VFS initialization. Do you have the `data` and `options` folders in the executable directory? Also, is the `ArenaPath` in `options/options.txt` pointing to a valid `ARENA` installation? I think the out of range exception is being thrown [here](https://github.com/afritz1/OpenTESArena/blob/7adc74dfe66df3316d64c9390007c8d4ca57ca20/OpenTESArena/src/Utilities/KvpTextMap.cpp#L32) during options parsing because it couldn't find `options.txt`, so the file is empty.

**Comment by Translator5** [comment]
Where should I start the x-exe from?
`.../OpenTESArena-master` or `.../OpenTESArena-master/build`?

If I start the game from the build folder the followind pops up;
`terminate called after throwing an instance of 'std::out_of_range'`

If I start the game from the master folder;
```
Game: Initializing (Platform: Linux).
File error: Could not open "options/options.txt".

```

**Comment by afritz1** [comment]
I believe CMake just puts the `TESArena` executable in the master directory, so that's where it should be run from.

The `data` and `options` folders within the `data` folder should be brought up one folder. I'm sorry about the name of the upper-level `data` folder being a little misleading. It's a bad name, and I should change it to `data_files` or something. I intended that to just be a container that I manually place into releases.

I don't remember there being a `build` directory, but I haven't really standardized the building process between Linux and Windows yet either, so that will be better eventually (in other words, I haven't switched to CMake on Windows yet).

**Comment by afritz1** [comment]
I moved the `data` and `options` folders into the repository's root directory, so it should be easier for the executable to find them now.

The directory should look something like this when you run the executable:
```
OpenTESArena-master
    cmake
    components
    data
        ARENA
        eawpats
        kernels
        text
        icon.ppm
    ...
    options
        options.txt
    TESArena
    ...
```

**Comment by Translator5** [comment]
> I don't remember there being a build directory, but I haven't really standardized the building process between Linux and Windows yet either, so that will be better eventually (in other words, I haven't switched to CMake on Windows yet).

I used the terminal entries of https://travis-ci.org/afritz1/OpenTESArena
There have been a `mkdir build && cd build`

**Comment by afritz1** [comment]
Yeah, `travis.yml` and `CMakeLists.txt` don't have to do the same thing. Travis CI just compiles the code for correctness and doesn't run the executable, so it doesn't need to be organized for viewing by a user.

Have you gotten the executable to run yet? Any other problems?

**Comment by Translator5** [comment]
> Have you gotten the executable to run yet? Any other problems?
It works! Thanks for creating this!

**Comment by afritz1** [comment]
No problem! I'm glad it works on other computers besides my own. It's still pretty early in development, but I work on it when I can. If anyone would like to make any changes, don't hesitate to open a pull request. It's my first game engine so a lot of the code consists of first attempts and experiments.

**Comment by Ragora** [comment]
> I don't remember there being a build directory, but I haven't really standardized the building process between Linux and Windows yet either, so that will be better eventually (in other words, I haven't switched to CMake on Windows yet).

The Travis build just does out of an tree build by creating a build folder then running cmake out of it. It doesn't really need to, this just prevents your source tree from being clogged with object files.

> Just tried out the Linux64 Version -> works fine!

Glad to know the binaries I made are working. I had built them and it looked like they worked on the intended systems, but I never assume 100% certainty.
