### ISSUE TITLE
Gap exists between fists and interface

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#68]
There's a one pixel gap between the fists and the interface when you ready the fists. It isn't there in the original game.

**Comment by afritz1** [comment]
I noticed this gap, too. And it actually is present in the original game, but there's a black line instead, probably due to an off-by-one bug in the renderer. The dimensions I'm using for drawing the game interface and the fists are the same as in the original game, so this one pixel gap is a result of my renderer not having the same off-by-one bug.

I suppose I could just translate all weapon animation Y coordinates down by one pixel, and that would fix it for all of them.

**Comment by Allofich** [comment]
Oh, you're right! Well, I would support doing it the way the original game does and put a black line to fill the gap, but it's your project.

**Comment by afritz1** [comment]
I've noticed a few off-by-one bugs in Daggerfall's renderer, like when a sprite is partially off the side of the screen and it's missing a row or column of pixels. It's kind of a gray area on how to address it, if it should be considered desirable behavior or not. Same deal with replicating Morrowind's bugs in OpenMW.

I'm leaning towards a simple fix like translating it down one pixel instead of adding a black line, because off-by-one errors are generally an oversight and are not desirable. It could be fixed either way, because again, it's a gray area.

**Comment by Allofich** [comment]
Well I haven't really thought the issue through, so I would say do what you think is best. And yes, that comes up all the time with the Daggerfall and Morrowind remakes, too. I like keeping to the original behavior unless it's a bug, but like you said, whether it's a bug is a gray area.

**Comment by afritz1** [comment]
Fixed in commit 820c583e71e706c6c99b3da623bd8fe427269d0a.
