### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by Translator5** [afritz1/OpenTESArena#72]
Hi there, today I installed your 0.4.0 release and found that the game is going to be really nice!
So I would like to ask you (all devs.) if it is possible to build in some features /modifications in the future.

- Better movement: A and D keys will move the player to the direction instead of rotating the camera
- Camera improvements: possibility to move the camera using the mouse but also the keys Q and E.
Also a optional possibility to move the camera 45 ° up and down -> this would add some immersion and make some things a bit easier. e.g. you can pickup this looking at the floor instead of standing meters away of them and have a better view on loot in general as well as the sky.
- Translation support: there is already a full translation for ARENA into the Russian language, but there are some fails concerning the generated dialogs of NPCs (The story-line scenes are fine). I think this is caused by the NPC-related texts, which are generated using ASCI-numbers. And because Russian uses the cyrillic-letters it cause a lot of bugs in the official game. Maybe this issue would be fix-able in OpenTESArena?
- Quicksave / Quickload using F5 and F9
- Toggle fullscreen using F10

**Comment by afritz1** [comment]
Your first two points are already covered by my rough draft modern interface mode. Try setting `ModernInterface` to `True` in options.txt (in recent commits, I added more options to the menu, so you can change it there instead). I don't think we want any vertical camera look in classic mode, so any new modifications would only be in modern mode.

I know of the Russian translation, and isn't there a French translation as well? My focus will just be on the English version until most of the project is done, though, because there's little reason to move my focus over to localization if I can't even load most of the English data yet. We would also need new fonts for each alphabet, and that's outside the project scope right now.

I've already thought about quicksave and quickload. Those are great features very common today. There isn't really anything to save yet, so they will be left for later.

Toggling fullscreen is another nice feature, and it should be pretty easy with SDL2. I think I'd probably just add windowed mode and borderless fullscreen at first.

**Comment by Translator5** [comment]
Nice to hear.
Whats about shortcuts for the user-interface -> C for character, I for Inventory ...

**Comment by afritz1** [comment]
The hotkeys are in the [Readme](https://github.com/afritz1/OpenTESArena/blob/481b8f59353e5060536230b393dfca343c355f1d/README.md#current-status-). Everyone should always read the Readme first!

**Comment by afritz1** [comment]
The short term features in this issue have been implemented as of commit c191d06db98c1f0ff0d62aeba801b6a15c0d8acd.

I don't have any translation support on the radar right now, and there's not really anything to load or save yet, so those features will be approached at a later point after other low-level features have been implemented. It certainly would be cool to support translations like Russian and French, but it's just too early to consider them yet.
