### ISSUE TITLE
No messages after choosing a race during character creation

### ISSUE THREAD

**Issue by Thunderforge** [afritz1/OpenTESArena#76]
In vanilla Arena, clicking on a land to choose a race gives you a choice asking if you're sure you want that race, and then several messages about your chosen race and class. 

<img width="752" alt="creation screen 1" src="https://user-images.githubusercontent.com/6200170/28001235-bcb1ad28-64f0-11e7-8bde-3e4171aa4de6.png">
<img width="752" alt="creation screen 2" src="https://user-images.githubusercontent.com/6200170/28001237-bcc6233e-64f0-11e7-9b00-6683e859c0aa.png">
<img width="752" alt="creation screen 3" src="https://user-images.githubusercontent.com/6200170/28001238-bcca9b80-64f0-11e7-8441-f33280d8022e.png">
<img width="752" alt="creation screen 4" src="https://user-images.githubusercontent.com/6200170/28001239-bcce2656-64f0-11e7-901e-46a5173ca47a.png">
<img width="752" alt="creation screen 5" src="https://user-images.githubusercontent.com/6200170/28001240-bcd1263a-64f0-11e7-9325-8f54252f6d41.png">
<img width="752" alt="creation screen 6" src="https://user-images.githubusercontent.com/6200170/28001255-d1a62db2-64f0-11e7-96a5-e0f0f85b4e91.png">

These do not currently appear in OpenTESArena. As soon as you click on a land, you go straight to the stat allocation screen without any messages.

**Comment by afritz1** [comment]
Thanks for pointing that out. It's not implemented yet. I have some plans ready for the next iteration of UI code and I might delve into that in the next couple weeks when I get a chance. I was thinking of implementing the character questions first, so there's that, too.

**Comment by Thunderforge** [comment]
I figured I'd point that out since it didn't look like it was on [this roadmap](https://github.com/afritz1/OpenTESArena/wiki#scope) and selecting races was already pretty complete.

In general, do we want to create issues for missing features? Or is there some other way we'd like to handle them?

**Comment by afritz1** [comment]
The roadmap is just kind of a rough list of ideas to let me give some general direction to the community, so it's not really meant as a definitive checklist yet. Some things are not on it yet, some things are completed out of order (like the automap), etc.. At this point, it really depends on what I think I can implement at a given time. If I think I can do something, then I work on it, and I revise the roadmap when there's something to write about.

I haven't really made a decision yet on handling missing features, so I'm still figuring out what I want to do. I've been keeping a mental model of things to do and I just figured that I would implement features like the pop-ups in character creation once I had the relevant tools done in the code. I've spent enough time playing Arena and making note of gameplay behavior in the last couple years to know most of the ins-and-outs, so don't worry about me forgetting features!

I actually intended for the issue you brought up to count as part of "better pop-up functionality" under the current priority, but I guess that's not immediately clear for newcomers to the project. I intentionally left it for later a few months ago since I figured getting the software renderer working was higher priority than player stats and UI presentation.

On a related note, I haven't gotten to the point yet where I want to precisely define which bugs/exploits to leave in the game (like with OpenMW) because there are too many low-level components left to do first (collision, more UI, more rendering, city generation, etc.). It will eventually depend on how closely we want to approximate parts of Arena's behavior that could be considered questionable or broken.

**Comment by afritz1** [comment]
See commits 4f474fca1f8e35797045b467f8050daa678bd2b5 and 801749b8d6f290297de05f9f668c6d2c033243a1. The missing messages brought up in this issue have been added, but there are still a couple more to add in the attributes screen, so I'll consider this issue finished once those are added.

**Comment by afritz1** [comment]
See commit 331bcdf00f222bf9a0b01fd35585853bb960d138. Although there isn't any stat allocation yet, the pop-up messages are all there now, so I think we can consider this issue closed. The remaining parts of character creation (class questions and stat allocation) will be implemented at some point later on, and highlighted hotkeys are on the to-do list as well (which will require some changes to the text box code).
