### ISSUE TITLE
Copy options.txt to user's preferences location

### ISSUE THREAD

**Issue by Thunderforge** [afritz1/OpenTESArena#84]
OpenTESArena assumes that `options/options.txt` will be in the same directory as the executable. This will not be a long term solution. On Windows if we install this app in C:/Program Files, users may be unable to edit this file without administrator rights. Furthermore, Mac applications in .app format cannot edit files contained within themselves, and non-admin users generally cannot edit them at all. And of course, if two users on the same computer want different settings, they would be overwriting each other's changes.

Every user has a preferences location that they are guaranteed to be able to write to. I suggest that we bundle a copy of options.txt, then the app copies it to the user's preferences location (if it doesn't already exist there), then reads from that location. This is exactly what projects like OpenMW use for their preferences.

The preferences location can be found with [SDL_GetPrefPath()](https://wiki.libsdl.org/SDL_GetPrefPath?highlight=%28%5CbCategoryFilesystem%5Cb%29%7C%28CategoryEnum%29%7C%28CategoryStruct%29), which takes the organization name and game name as parameters. On macOS, it points to  `~/Library/Application Support/OrganizationName/AppName/`. As with `SDL_GetBasePath()`, we should be calling `SDL_free()` when we are done.

If we don't want to use an organization name, I suppose we could use "OpenTESArena" as the organization and "AppName" as whatever subdirectory we want to use. So `SDL_GetPrefPath("OpenTESArena", "options")` for instance.

**Comment by afritz1** [comment]
That's a good idea. I've had trouble editing a `dosbox.conf` before when it was somewhere in Program Files (because of admin privileges), so I know what you're talking about. The `Game` class should probably have an `optionsPath` member that points to `SDL_GetPrefPath("OpenTESArena", "options")` like you suggested.

I should also print the path out in the console since it can be hard to find those places on Windows sometimes (AppData/Local/VirtualStore/...)

**Comment by Thunderforge** [comment]
Printing the path to the console is an excellent idea. Perhaps print either that we are copying it over or that it exists and we are reading from that location. In both cases, we would be saying the final location.

**Comment by afritz1** [comment]
Looks like Linux might only include the application name in the path, so maybe I need to append "options" to the string returned by `SDL_GetPrefPath("OpenTESArena", "OpenTESArena")` instead.

**Comment by Thunderforge** [comment]
That behavior seems contrary to [this patch](https://bugzilla.libsdl.org/show_bug.cgi?id=2173), which seems to have been [applied to the source code](https://github.com/spurious/SDL-mirror/blob/13666b37a08a78bb209b5c584f74846f7e7b5cf2/src/filesystem/unix/SDL_sysfilesystem.c#L168). I also found forum posts such as [this one](http://forums.libsdl.org/viewtopic.php?t=9870), which say that Linux was using both the organization and app name.

Are we both using the same version of SDL? I'm using 2.0.5.

**Comment by afritz1** [comment]
I'm using SDL 2.0.4, which is from Jan. 2016, so it has that patch in it. No worries then.

**Comment by afritz1** [comment]
Hmm, so this is actually causing a problem for the development environment, since 1) Running in Visual Studio, 2) Running debug build, and 3) Running release build all reference the same `options.txt`.

How would it only look in the `SDL_GetPrefPath()` when it's running outside of Visual Studio? I'll need to look more into this tomorrow.

**Comment by Thunderforge** [comment]
Where would the original be located in this case? I assume we would need to have one in order to copy it somewhere else.

Personally, I like the idea of having my IDE, debug build, and release build all using the same options.txt, but to each their own. I do think that end users shouldn't have to think about where it's located unless they want to enable experimental options not otherwise available in the UI.

**Comment by afritz1** [comment]
The original would be generated by the program if no others exist in either a local `options` folder or in the global `options` folder through `SDL_GetPrefPath()`. The program might do a check on the parsed `options.txt` to verify that it has all the relevant keys and values before the program continues.

One reason for having them separate would be if I want it to start in windowed mode while developing, and to start in fullscreen when running the release build without needing to fiddle with `options.txt` in between. I might also want the resolution scale lower in debug mode because the software renderer is pretty slow in that case.

People developing OpenTESArena would get their local copy of `options/options.txt` (that is, it comes with the repository and is copied by CMake), but the release build would not be shipped with one, instead having it be generated if it doesn't exist. This makes a slight dependency between the one generated by the program and the one stored in the repository, but they change infrequently enough that it's not a problem to maintain.

**Comment by Thunderforge** [comment]
> The original would be generated by the program if no others exist

We would need to write this code to generate an options file, correct? Right now, it looks like we are using the options.txt file that is distributed with the source, and initially I assumed we would just copy that "template" version to the location. That also saves a bit of awkwardness in that a first time user would have to run the app, let it generate the file, then copy the file where they want it to go.

A possible alternative to an override system would be to have different options.txt files, like options-debug.txt or something, all in the preferences location. That would mean we could check all in the same file location.

**Comment by afritz1** [comment]
I've been looking around in OpenMW's code recently, so I'm more comfortable doing it their way now. I plan on changing how options.txt is handled soon.

What should we do in the case where the global options.txt exists but it is older than the one in a new release? Since OpenTESArena is still in early development, we should expect the key-value pairs listed in the file to change frequently, so it needs to be able to handle cases like this.

I'm not sure how OpenMW handles this because I don't see any version numbers in their settings.cfg.

**Comment by kcat** [comment]
A global user-editable config doesn't make sense, since users don't/shouldn't have permission to modify global files. If following the OpenMW style, the global config should just be the config defaults, and users would make user-specific config files to override the default settings.

In Windows terms, you'd install into ```C:\Program Files\OpenTESArena``` or something, which includes the executable, config-defaults.txt, and whatever other non-changing files are needed. If the user wants to change an option, they would create/edit something like ```C:\Users\<username>\Application Data\OpenTESArena\config.txt``` that has just the settings they want to change (these paths are the typical ones Windows uses; they may be different and there's WinAPI functions to get what they really are). When a user updates, they'd overwrite the files in ```Program Files``` (including the config-defaults.txt), leaving their custom settings in ```Application Data``` alone.

**Comment by afritz1** [comment]
That sounds reasonable. I guess there's no perfect solution to this problem, because it appears that there are trade-offs to each. If we go with your suggestion, then users will need to manually create an options.txt in their `AppData/Roaming/OpenTESArena/options` folder if they want changes to options before the first time they run the program. This seems a little inconvenient to me, especially for users not familiar with the Local/LocalLow/Roaming folders and things.

In any case, the program will always display the path to the options file(s) it is using, which should always be at least options-default.txt next to the executable, and `<username>/AppData/Roaming/OpenTESArena/options/options.txt` if there are changes (I'm assuming all users will have at least _some_ changes).

**Comment by kcat** [comment]
> If we go with your suggestion, then users will need to manually create an options.txt in their AppData/Roaming/OpenTESArena/options folder if they want changes to options before the first time they run the program.

This is where a GUI configuration app would be useful. They're not the easiest thing to make (I'd recommend trying Qt5 if you want to go for it), but will be greatly appreciated by users regardless of how the config file hierarchy is structured. OpenMW allows modifying some options in its launcher, with talk of adding most/all other settings to it, which needs to be run first anyway to deal with finding (or installing) the actual game's data.

**Comment by afritz1** [comment]
This issue is mostly resolved for now with commit 820ea60b2f1f249b347d32b39ffb96676922b633. The automated creation of an `options-changes.txt` file _before_ OpenTESArena is run will happen once a wizard is created for the project.
